defaults:
  - optimizer_template: adam
  - scheduler_template: step_lr

_target_: models.misc.LitPredictorModel

main:
  _target_: models.misc.PredictorModel

  predictor:
    _target_: models.predictors.mlp.MLPPredictor
    layers: [8800, 4000, 1500, 600, 200]
    activation:
      _target_: torch.nn.ReLU

field: bow

criterion:
  _target_: torch.nn.CrossEntropyLoss
