_target_: models.auto_concept_bottleneck.LitAutoConceptBottleneckModel

main:
  _target_: models.auto_concept_bottleneck.AutoConceptBottleneckModel

  feature_extractor:
    _target_: models.feature_extractors.torchvision.TorchvisionFeatureExtractor
    model: inception_v3
    weights: IMAGENET1K_V1
    out_features: 10

  concept_extractor:
    _target_: models.concept_extractors.cnn.ConceptExtractorSingleCNN
    vocab_size: 30
    embed_dim: 8
    n_filters: 512
    filter_size: 5
    out_features: 10

  predictor:
    _target_: models.predictors.mlp.MLPPredictor
    layers: [10, 9]
    activation:
      _target_: torch.nn.ReLU

  interim_activation:
    _target_: functional.gumbel.GumbelSigmoid
    step: 15
    t: 1.0
    rate: 0.007
    min_val: 0.5

  temperature: 1.

dist_weight: 1.0

criterion_task:
  _target_: torch.nn.CrossEntropyLoss

criterion_tie:
  _target_: functional.loss.JensenShannonDivergenceLoss
tie_weight: 10.0

mix_tie_epoch: null

tie_loss_wrt_concepts: true

optimizer_model_template:
  _target_: functools.partial
  _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.02

optimizer_concept_extractor_template:
  _target_: functools.partial
  _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.AdamW
  lr: 6e-3
  weight_decay: 0.03

scheduler_model_template:
  _target_: functools.partial
  _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.lr_scheduler.MultiStepLR
  milestones: [5, 7]
  gamma: 0.1

scheduler_concept_extractor_template:
  _target_: functools.partial
  _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.lr_scheduler.MultiStepLR
  milestones: [6, 8]
  gamma: 0.3
