_target_: models.base.LitBaseModel

main:
  _target_: models.base.BaseModel

  extractor:
    _target_: models.feature_extractors.torchvision.TorchvisionFeatureExtractor
    model: inception_v3
    weights: IMAGENET1K_V1
    out_features: 10

  predictor:
    _target_: models.predictors.mlp.MLPPredictor
    layers: [10, 9]
    activation:
      _target_: torch.nn.ReLU

  # interim_activation:
    # _target_: functional.gumbel.GumbelSigmoid
    # _target_: torch.nn.Sigmoid
    # _target_: torch.nn.ReLU
  interim_activation:
    # _target_: torch.nn.Sigmoid
    _target_: functional.gumbel.GumbelSigmoid
    step: 15
    t: 1.0
    rate: 0.007
    min_val: 0.001


criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer_template:
  _target_: functools.partial
  _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.02

scheduler_template:
  _target_: functools.partial
  _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.lr_scheduler.MultiStepLR
  milestones: [5, 7]
  gamma: 0.1
