_target_: models.concept_bottleneck.LitConceptBottleneckModel

main:
  _target_: models.base.BaseModel

  extractor:
    _target_: models.feature_extractors.torchvision.TorchvisionFeatureExtractor
    model: inception_v3
    weights: IMAGENET1K_V1
    out_features: 6

  predictor:
    _target_: models.predictors.mlp.MLPPredictor
    layers: [6, 9]
    activation:
      _target_: torch.nn.ReLU

  interim_activation:
    _target_: torch.nn.Sigmoid

criterion_task:
  _target_: torch.nn.CrossEntropyLoss

criterion_concept:
  _target_: torch.nn.BCELoss
  reduction: none

lambda_p: 0.01

optimizer_template:
  _target_: functools.partial
  _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.02

scheduler_template:
  _target_: functools.partial
  _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.lr_scheduler.MultiStepLR
  milestones: [5, 7]
  gamma: 0.1
