defaults:
  - base

_target_: datasets.mimic_dataset.MimicDataModule

img_dir: data/mimic-cxr/images
annotation_path: data/mimic-cxr/annotation.csv
collate_fn:
  _target_: datasets.collators.CollateEmulator
