defaults:
  - base

_target_: datasets.public_dataset.JointDataModule

annotation_path: data/captions_merged.csv
img_root: data/merged_files
CUB_dir: data/CUB_200_2011
mix_with_mscoco: False
use_val_for_train: False
collate_fn:
  _target_: datasets.collators.CollateEmulator
