defaults:
  - dataset: public
  - model: M01
  - _self_

name: Experiment
timestamp: ${now:%Y-%m-%d}/${now:%H-%M-%S}
accelerator: gpu
devices: [0]
debug: False
seed: 42
max_epochs: 200
log_every_n_steps: 5
epoch_freeze_backbone: null

early_stopper:
  _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  monitor: loss/val
  mode: min
  patience: 5

hydra:
  job:
    chdir: True
