defaults:
  - dataset: public
  - model: M01
  - _self_

name: Experiment
timestamp: ${now:%Y-%m-%d}/${now:%H-%M-%S}
accelerator: gpu
devices: [0]
debug: False
seed: 42
max_epochs: 200

hydra:
  job:
    chdir: True
